name: fl_jpush_android
description: JPush integrated vendor push channel
version: 0.0.1
repository: https://github.com/Wayaer/fl_jpush_android.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fl.jpush.android
        pluginClass: JPushAndroidPlugin
